FROM php:8.1.1-apache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN docker-php-ext-install pdo && docker-php-ext-enable pdo
RUN docker-php-ext-install pdo_mysql && docker-php-ext-enable pdo_mysql

#below, php modules recommanded for wordpress
RUN docker-php-ext-install exif && docker-php-ext-enable exif
RUN docker-php-ext-install gd && docker-php-ext-enable gd
RUN apt-get update && apt install -y libzip-dev libpng-dev
RUN docker-php-ext-install zip && docker-php-ext-enable zip
RUN a2enmod rewrite
